---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-watchdog
  namespace: velero
  labels:
    app: velero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: velero-watchdog
  namespace: velero
  labels:
    app: velero
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "list"
      - "get"
      - "watch"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: velero-watchdog
  namespace: velero
  labels:
    app: velero
subjects:
  - kind: ServiceAccount
    namespace: velero
    name: velero-watchdog
roleRef:
  kind: Role
  name: velero-watchdog
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: velero-watchdog
  namespace: velero
  labels:
    app: velero
spec:
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app: velero
        spec:
          serviceAccountName: velero-watchdog
          imagePullSecrets:
            - name: staffbase-artifactory
          containers:
            - name: velero-watchdog
              image: veerendra2/velero-watchdog:latest
              imagePullPolicy: IfNotPresent
              securityContext:
                allowPrivilegeEscalation: false
                capabilities:
                  drop: [ALL]
                privileged: false
                readOnlyRootFilesystem: true
                runAsNonRoot: true
                seccompProfile:
                  type: RuntimeDefault
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              resources:
                requests:
                  memory: "300Mi"
                  cpu: "200m"
                limits:
                  memory: "300Mi"
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
          securityContext:
            runAsUser: 1001
            runAsGroup: 1001
            fsGroup: 1001
